/**
 * BAT Profiler — diagnostic report builder
 * ========================================
 *
 * Turns a stored run into a few KB of plain text you can paste to
 * somebody who needs to work out why the box ran out of memory.
 *
 * The design constraint that shapes everything here: **an OOM kill
 * leaves no error behind**. The kernel SIGKILLs the process, no
 * exception is raised, no `execution_error` is sent, the websocket just
 * stops. So the report can never be generated by the thing that died —
 * it is reconstructed afterwards, in the browser, from the records that
 * were streamed to localStorage before the lights went out.
 *
 * That dictates three things this file does that a naive dump wouldn't:
 *
 * 1. **It names the node that was running when the process died.** The
 *    last *completed* node is not the culprit — the culprit is the one
 *    after it, which never got to report. We track that separately from
 *    ComfyUI's own `executing` event and surface it as the verdict.
 * 2. **It reports headroom, not just usage.** "18 GB VRAM" means
 *    nothing without "of 24 GB". Every figure is against its ceiling.
 * 3. **It separates peak from held.** A single node peaking high is a
 *    different bug from twenty nodes each keeping half a gigabyte, and
 *    the fixes are opposite. Both get their own table.
 *
 * Pure and DOM-free so it can be exercised head-less under quickjs.
 */

const BAR_W = 22;

function fmtB(n, signed) {
  if (n === null || n === undefined || Number.isNaN(n)) return "—";
  const sign = signed && n > 0 ? "+" : n < 0 ? "-" : "";
  let v = Math.abs(n);
  if (v < 1024) return `${sign}${v} B`;
  const u = ["KB", "MB", "GB", "TB"];
  let i = -1;
  do { v /= 1024; i++; } while (v >= 1024 && i < u.length - 1);
  return `${sign}${v < 10 ? v.toFixed(2) : v.toFixed(1)} ${u[i]}`;
}

function fmtT(s) {
  if (s === null || s === undefined || Number.isNaN(s)) return "—";
  if (s < 1) return `${Math.round(s * 1000)}ms`;
  if (s < 60) return `${s.toFixed(1)}s`;
  const m = Math.floor(s / 60);
  if (m < 60) return `${m}m${String(Math.round(s % 60)).padStart(2, "0")}s`;
  return `${Math.floor(m / 60)}h${String(m % 60).padStart(2, "0")}m`;
}

function clock(epoch) {
  if (!epoch) return "—";
  const d = new Date(epoch * 1000);
  const p = (n) => String(n).padStart(2, "0");
  return `${p(d.getHours())}:${p(d.getMinutes())}:${p(d.getSeconds())}`;
}

function pct(v, total) {
  if (!total) return "";
  return `${((v / total) * 100).toFixed(1)}%`;
}

function bar(v, max) {
  if (!max || v <= 0) return "".padEnd(BAR_W, "·");
  const n = Math.max(1, Math.min(BAR_W, Math.round((v / max) * BAR_W)));
  return "█".repeat(n).padEnd(BAR_W, "·");
}

function pad(s, n) {
  s = String(s === null || s === undefined ? "" : s);
  return s.length > n ? s.slice(0, n - 1) + "…" : s.padEnd(n);
}

function padL(s, n) {
  s = String(s === null || s === undefined ? "" : s);
  return s.length > n ? s.slice(0, n) : s.padStart(n);
}

function nodeLabel(run, rec) {
  const title = run.titles?.[rec.node_id];
  if (title && title !== rec.class_type) return `${title} (${rec.class_type})`;
  return rec.class_type || "?";
}

/** Peak of a field across the sample series, with the time it happened. */
function peakOf(samples, key) {
  let best = { v: 0, t: null, node: null };
  for (const s of samples) {
    const v = s[key] || 0;
    if (v > best.v) best = { v, t: s.t, node: s.node };
  }
  return best;
}

/** Last non-null value of a field — used for the ceilings, which are
 *  only sampled occasionally. */
function ceilingOf(samples, key, fallback) {
  for (let i = samples.length - 1; i >= 0; i--) {
    if (samples[i][key]) return samples[i][key];
  }
  return fallback || 0;
}

/**
 * Compress the 5 Hz series into a readable number of rows.
 *
 * Max within each bucket rather than mean: a spike that gets you killed
 * must not be averaged away by the four calm samples either side of it.
 */
function trajectory(samples, rows, ramMax, vramMax, run) {
  if (samples.length < 2) return [];
  const t0 = samples[0].t;
  const t1 = samples[samples.length - 1].t;
  const span = Math.max(t1 - t0, 0.001);
  const out = [];
  for (let i = 0; i < rows; i++) {
    const lo = t0 + (span * i) / rows;
    const hi = t0 + (span * (i + 1)) / rows;
    const slice = samples.filter((s) => s.t >= lo && (s.t < hi || i === rows - 1));
    if (!slice.length) continue;
    let sys = 0, vram = 0, node = null;
    for (const s of slice) {
      if ((s.sys || 0) > sys) sys = s.sys || 0;
      if ((s.vram || 0) > vram) { vram = s.vram || 0; }
      if (s.node) node = s.node;
    }
    const label = node ? (run.titles?.[node] || run.nodes?.[node]?.class_type || `#${node}`) : "";
    out.push(
      `  +${padL(fmtT(lo - t0), 7)}  ${padL(fmtB(sys), 9)} ${padL(pct(sys, ramMax), 6)}  ` +
      `${padL(fmtB(vram), 9)} ${padL(pct(vram, vramMax), 6)}  ${pad(label, 24)}`
    );
  }
  return out;
}

function table(rows, header) {
  if (!rows.length) return [];
  return [header, ...rows];
}

/**
 * @param {object} o
 * @param {object} o.run          the run to report on (from ProfilerStore)
 * @param {number} o.runCount     how many runs are stored for this workflow
 * @param {string} o.workflowName display name of the workflow
 * @param {object} o.system       /system_stats payload, or null
 * @param {object} o.config       profiler settings in force
 * @returns {string}
 */
export function buildReport({ run, runCount, workflowName, system, config }) {
  if (!run) return "BAT Profiler: no run recorded for this workflow yet.";

  const L = [];
  const samples = run.samples || [];
  const recs = Object.values(run.nodes || {});
  const executed = recs.filter((n) => !n.cached && !n.skipped);

  // ── ceilings ──────────────────────────────────────────────────────
  const dev = system?.devices?.[0];
  const ramMax = ceilingOf(samples, "sys_total", run.baseline?.sys_total || system?.system?.ram_total || 0);
  const vramMax = ceilingOf(samples, "dev_total", run.baseline?.dev_total || dev?.vram_total || 0);

  const ramPeak = peakOf(samples, "sys");
  const rssPeak = peakOf(samples, "ram");
  const vramPeak = peakOf(samples, "vram");
  const resPeak = peakOf(samples, "res");
  const t0 = samples.length ? samples[0].t : run.started;

  // ── verdict ───────────────────────────────────────────────────────
  // The last node to *complete* is not the suspect. The suspect is the
  // one that started and never reported back.
  const inflight = run.inflight;
  const died = inflight && !(run.nodes || {})[inflight.node_id];
  const lost = run.status === "lost" || (run.status === "running" && !run.ended);

  L.push("BAT Profiler report");
  L.push("═".repeat(72));
  L.push(`WORKFLOW  ${workflowName || run.workflow || "—"}`);
  L.push(`RUN       started ${clock(run.started)}` +
         (run.ended ? ` · ended ${clock(run.ended)} · ${fmtT(run.ended - run.started)}` : "") +
         `   (${runCount} run${runCount === 1 ? "" : "s"} stored)`);

  let verdict;
  if (lost) {
    verdict = "DID NOT FINISH — the backend stopped responding mid-run.\n" +
              "          No error was reported, which is the signature of an OOM kill\n" +
              "          (SIGKILL raises nothing) or a hard crash.";
  } else if (run.status === "error") {
    verdict = "ENDED IN ERROR.";
  } else if (run.status === "interrupted") {
    verdict = "INTERRUPTED.";
  } else {
    verdict = "Completed normally.";
  }
  L.push(`STATUS    ${verdict}`);

  if (died) {
    const label = inflight.title
      ? `${inflight.title} (${inflight.class_type || "?"})`
      : (inflight.class_type || "?");
    L.push(`DIED IN   node ${inflight.node_id} — ${label}`);
    L.push(`          started ${clock(inflight.t)}, ran ${fmtT((run.lastSeen || inflight.t) - inflight.t)} ` +
           `without completing.`);
    L.push(`          ^ this node is the suspect; the rows below are what it inherited.`);
  } else if (lost) {
    L.push("DIED IN   unknown — no node-start was recorded before the stream ended.");
  }
  L.push("");

  // ── machine ───────────────────────────────────────────────────────
  L.push("MACHINE");
  if (dev) L.push(`  GPU       ${dev.name}`);
  L.push(`  RAM       ${fmtB(ramMax)} total` +
         (ramPeak.v ? `   peak seen ${fmtB(ramPeak.v)} (${pct(ramPeak.v, ramMax)})` +
                      `  at +${fmtT(ramPeak.t - t0)}` : ""));
  L.push(`  VRAM      ${fmtB(vramMax)} total` +
         (vramPeak.v ? `   peak allocated ${fmtB(vramPeak.v)} (${pct(vramPeak.v, vramMax)})` +
                       `  at +${fmtT(vramPeak.t - t0)}` : ""));
  if (resPeak.v) {
    L.push(`            torch reserved peaked ${fmtB(resPeak.v)} (${pct(resPeak.v, vramMax)})` +
           ` — reserved, not allocated, is what the driver actually holds.`);
  }
  if (rssPeak.v) L.push(`  ComfyUI   RSS peaked ${fmtB(rssPeak.v)}`);
  if (run.baseline?.sys) {
    L.push(`  Baseline  ${fmtB(run.baseline.sys)} RAM / ${fmtB(run.baseline.vram || 0)} VRAM before the run started`);
  }
  if (system?.system) {
    const s = system.system;
    L.push(`  Versions  ComfyUI ${s.comfyui_version || "?"} · torch ${s.pytorch_version || "?"}`);
    // Keep the values, not just the flag names: "--reserve-vram 2" is
    // the useful string, "--reserve-vram" tells you nothing.
    const argv = (s.argv || []).slice(1);
    if (argv.length) {
      let line = argv.join(" ");
      if (line.length > 200) line = line.slice(0, 197) + "…";
      L.push(`  Launched  ${line}`);
    }
  }
  if (config) {
    L.push(`  Profiler  ${config.sync_cuda ? "GPU-synced" : "no GPU sync"}` +
           `${config.reset_peak === false ? " · peak reset OFF (peaks are cumulative)" : ""}`);
  }
  L.push("");

  // ── headroom warning ──────────────────────────────────────────────
  const ramTight = ramMax && ramPeak.v / ramMax > 0.92;
  const vramTight = vramMax && vramPeak.v / vramMax > 0.92;
  if (ramTight || vramTight) {
    L.push("HEADROOM");
    if (ramTight) L.push(`  ! System RAM reached ${pct(ramPeak.v, ramMax)} of the machine. ` +
                         `This is what the OOM killer watches.`);
    if (vramTight) L.push(`  ! VRAM reached ${pct(vramPeak.v, vramMax)} of the card.`);
    L.push("");
  }

  // ── trajectory ────────────────────────────────────────────────────
  const traj = trajectory(samples, 18, ramMax, vramMax, run);
  if (traj.length) {
    L.push("TRAJECTORY  (peak within each slice — spikes are not averaged away)");
    L.push(`   ${padL("time", 7)}  ${padL("sys RAM", 9)} ${padL("of", 6)}  ` +
           `${padL("VRAM", 9)} ${padL("of", 6)}  node`);
    L.push(...traj);
    L.push("");
  } else if (samples.length < 2) {
    L.push("TRAJECTORY  (none — the run was shorter than one 5 Hz sample, " +
           "or the panel was shut)");
    L.push("");
  }

  // ── who peaked ────────────────────────────────────────────────────
  const byVram = executed.filter((n) => n.vram_peak > 0)
    .sort((a, b) => b.vram_peak - a.vram_peak).slice(0, 10);
  if (byVram.length) {
    const max = byVram[0].vram_peak;
    L.push("TOP BY VRAM PEAK  (transient high-water — what decides whether you OOM)");
    for (const n of byVram) {
      L.push(`  ${padL(fmtB(n.vram_peak), 9)} ${bar(n.vram_peak, max)} ` +
             `${pad(nodeLabel(run, n), 34)} ${padL(fmtT(n.duration), 7)}`);
    }
    L.push("");
  }

  const byRam = executed.filter((n) => n.ram_peak > 0)
    .sort((a, b) => b.ram_peak - a.ram_peak).slice(0, 8);
  if (byRam.length && !byVram.length) {
    const max = byRam[0].ram_peak;
    L.push("TOP BY RAM PEAK");
    for (const n of byRam) {
      L.push(`  ${padL(fmtB(n.ram_peak), 9)} ${bar(n.ram_peak, max)} ` +
             `${pad(nodeLabel(run, n), 34)} ${padL(fmtT(n.duration), 7)}`);
    }
    L.push("");
  }

  // ── who kept it ───────────────────────────────────────────────────
  // The other failure mode, and the one people miss: no single node
  // looks bad, but each hands on more than it received, and the graph
  // dies of accumulation two dozen nodes later.
  const holders = executed
    .filter((n) => (n.vram_delta || 0) > 0 || (n.ram_delta || 0) > 0)
    .sort((a, b) => ((b.vram_delta || 0) + (b.ram_delta || 0)) - ((a.vram_delta || 0) + (a.ram_delta || 0)))
    .slice(0, 10);
  if (holders.length) {
    const heldV = executed.reduce((a, n) => a + Math.max(0, n.vram_delta || 0), 0);
    const heldR = executed.reduce((a, n) => a + Math.max(0, n.ram_delta || 0), 0);
    L.push("STILL HELD AFTER RETURNING  (accumulation — the slow way to die)");
    L.push(`  total across the run: ${fmtB(heldV)} VRAM · ${fmtB(heldR)} RAM`);
    for (const n of holders) {
      L.push(`  ${padL(fmtB(n.vram_delta, true), 10)} VRAM ${padL(fmtB(n.ram_delta, true), 10)} RAM  ` +
             pad(nodeLabel(run, n), 34));
    }
    L.push("");
  }

  // ── slowest ───────────────────────────────────────────────────────
  const bySlow = executed.slice().sort((a, b) => b.duration - a.duration).slice(0, 6);
  if (bySlow.length) {
    L.push("SLOWEST");
    for (const n of bySlow) {
      L.push(`  ${padL(fmtT(n.duration), 8)}  ${pad(nodeLabel(run, n), 34)} ` +
             `out ${fmtB(n.bytes_out)}${n.desc_out ? ` (${n.desc_out})` : ""}`);
    }
    L.push("");
  }

  // ── shape of the run ──────────────────────────────────────────────
  const cached = recs.filter((n) => n.cached).length;
  const skipped = recs.filter((n) => n.skipped).length;
  L.push("RUN SHAPE");
  L.push(`  ${executed.length} executed · ${cached} cached · ${skipped} not run`);
  const biggest = executed.slice().sort((a, b) => b.bytes_out - a.bytes_out)[0];
  if (biggest?.bytes_out) {
    L.push(`  largest payload: ${fmtB(biggest.bytes_out)} from ${nodeLabel(run, biggest)}` +
           `${biggest.desc_out ? ` — ${biggest.desc_out}` : ""}`);
  }
  const io = executed.reduce((a, n) => a + (n.io_read || 0) + (n.io_write || 0), 0);
  if (io) L.push(`  disk I/O: ${fmtB(io)} total`);

  return L.join("\n");
}

export const _internals = { fmtB, fmtT, trajectory, peakOf, ceilingOf, bar };
